=== navalboyblue/skills-code-with-codespaces/extension/language/schemas/config/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "formatter": {
      "type": "string",
      "title": "Formatter",
      "description": "Specify the formatting ruleset for your code.",
      "enum": ["fiddle"],
      "default": "fiddle"
    },
    "eol": {
      "type": "string",
      "title": "End-of-line",
      "description": "Indicate whether we use the new line character (\"lf\", recommended) or Windows-style carriage-return-new-line (\"crlf\").",
      "enum": ["lf", "crlf"],
      "default": "lf"
    },
    "tabWidth": {
      "type": "number",
      "title": "Tab Width",
      "description": "Number of spaces to use for indentation.",
      "default": 2
    },
    "autoDoc": {
      "type": "boolean",
      "title": "AutoDoc",
      "description": "Automatically creates and updates IDL Doc style comments for routines on each save. You can freely use this if you don't have docs for your code. If you have docs, and they don't follow IDL Doc style, they are preserved.",
      "default": false
    },
    "autoFix": {
      "type": "boolean",
      "title": "Auto-fix Problems",
      "description": "If a problem can be automatically fixed, fix it prior to formatting. This does not apply to all problems detected by IDL.",
      "default": true
    },
    "styleAndFormat": {
      "type": "boolean",
      "title": "No Style or Formatting",
      "description": "When we process our code, do we apply our styles and format?\n\nIf this is set to `false` and `autoDoc` is enabled, then we add documentation to your code without changing anything else.",
      "default": true
    },
    "style": {
      "$ref": "v1.schema.json#/definitions/1.0.0-options"
    },
    "additionalProperties": false
  },
  "description": "Top-level preferences for how code gets formatted."
}

=== navalboyblue/skills-code-with-codespaces/idl/vscode/idl.json
{
  "tabWidth": 2,
  "style": {
    "quotes": "single",
    "methods": "dot",
    "keywords": "lower",
    "properties": "match",
    "control": "lower",
    "numbers": "lower",
    "hex": "lower",
    "octal": "lower",
    "binary": "lower",
    "routines": "match",
    "routineMethods": "camel",
    "structureNames": "pascal",
    "systemVariables": "lower",
    "localVariables": "match"
  },
  "autoFix": true,
  "autoDoc": true,
  "styleAndFormat": true
}

=== navalboyblue/skills-code-with-codespaces/idl/test/client-e2e/idl.json
{
  "tabWidth": 2,
  "style": {
    "quotes": "single",
    "methods": "dot",
    "keywords": "lower",
    "properties": "lower",
    "control": "lower",
    "numbers": "lower",
    "hex": "lower",
    "octal": "lower",
    "binary": "lower",
    "routines": "match",
    "systemVariables": "lower",
    "localVariables": "match"
  },
  "autoFix": true,
  "autoDoc": true,
  "styleAndFormat": true
}

=== navalboyblue/skills-code-with-codespaces/idl/test/scratch/idl.json
{
  "tabWidth": 2,
  "style": {
    "quotes": "single",
    "methods": "dot",
    "keywords": "lower",
    "properties": "camel",
    "control": "lower",
    "numbers": "lower",
    "hex": "lower",
    "octal": "lower",
    "binary": "lower",
    "routines": "match",
    "routineMethods": "match",
    "systemVariables": "lower",
    "structureNames": "pascal",
    "localVariables": "match"
  },
  "autoFix": true,
  "autoDoc": true,
  "styleAndFormat": true
}

=== navalboyblue/skills-code-with-codespaces/idl/test/scratch/dated/idl.json
{
  "formatter": "fiddle",
  "style": {
    "control": "upper",
    "keywords": "upper",
    "numbers": "upper",
    "properties": "upper",
    "systemVariables": "upper",
    "hex": "upper",
    "binary": "upper",
    "octal": "upper",
    "quotes": "double",
    "methods": "arrow",
    "routines": "match",
    "localVariables": "match"
  },
  "autoFix": true,
  "autoDoc": true,
  "eol": "lf"
}
